"""empty message

Revision ID: 198488b800b2
Revises: 561d9d5be6fa
Create Date: 2021-12-25 11:53:30.344854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198488b800b2'
down_revision = '561d9d5be6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_blog_authorat')
        batch_op.create_index(batch_op.f('ix_blog_author'), ['author'], unique=False)
        batch_op.drop_column('authorat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorat', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_blog_author'))
        batch_op.create_index('ix_blog_authorat', ['authorat'], unique=False)
        batch_op.drop_column('author')

    # ### end Alembic commands ###
