"""empty message

Revision ID: 561d9d5be6fa
Revises: abc7c4015167
Create Date: 2021-12-25 11:53:17.315820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561d9d5be6fa'
down_revision = 'abc7c4015167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorat', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_blog_author')
        batch_op.create_index(batch_op.f('ix_blog_authorat'), ['authorat'], unique=False)
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_blog_authorat'))
        batch_op.create_index('ix_blog_author', ['author'], unique=False)
        batch_op.drop_column('authorat')

    # ### end Alembic commands ###
