"""empty message

Revision ID: 939f6bcb0484
Revises: 198488b800b2
Create Date: 2022-01-06 12:57:56.659223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939f6bcb0484'
down_revision = '198488b800b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
