"""empty message

Revision ID: abc7c4015167
Revises: 47fa2d77bb36
Create Date: 2021-12-25 11:52:56.940154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc7c4015167'
down_revision = '47fa2d77bb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_blog_authoring')
        batch_op.create_index(batch_op.f('ix_blog_author'), ['author'], unique=False)
        batch_op.drop_column('authoring')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authoring', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_blog_author'))
        batch_op.create_index('ix_blog_authoring', ['authoring'], unique=False)
        batch_op.drop_column('author')

    # ### end Alembic commands ###
